name: output_demo
on:
  #Allows you to trigger manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      
